In [1]:
import numpy as np
import math

In [2]:
a = np.array ([1,2,3])
print(a)
print(a.ndim)

[1 2 3]
1


In [3]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b.shape

(2, 3)

In [5]:
a.dtype

dtype('int64')

In [6]:
c=np.array([2.2, 5,1.1])
c.dtype.name

'float64'

In [7]:
c

array([2.2, 5. , 1.1])

In [8]:
d= np.zeros((2,3))
print(d)
e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
np.random.rand(2,3)

array([[0.45948899, 0.87552005, 0.20324756],
       [0.04902541, 0.79921489, 0.27145753]])

In [10]:
f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [11]:
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [12]:
a =np.array([10,20,30,40])
b = np.array([1,2,3,4])
c= a-b
print(c)
d=a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [15]:
farenheit = np.array([0,-10,-5,-15,0])

celcius = (farenheit-32)*(5/9)
celcius

array([-17.77777778, -23.33333333, -20.55555556, -26.11111111,
       -17.77777778])

In [16]:
celcius >-20

array([ True, False, False, False,  True])

In [17]:
celcius %2 == 0

array([False, False, False, False, False])

In [22]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
print(A*B)
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [23]:
A.shape

(2, 2)

In [25]:
array1=np.array([[1,2,3], [4,5,6]])
print(array1.dtype)
array2=np.array([[7.1,8.2,9.1],[10.4,11.2,12.3]])
print(array2.dtype)

int64
float64


In [26]:
array3=array1+array2
print(array3)
print(array3.dtype)

[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
float64


In [27]:
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

79.3
18.3
8.1
13.216666666666667


In [29]:
b=np.arange(1,16,1).reshape(3,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [31]:
a=np.array([1,3,5,7])
a[2]

5

In [32]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
a[1,1]

4

In [34]:
np.array([a[0,0], a[1,1], a[2,1]])

array([1, 4, 6])

In [35]:
print(a[[0,1,2], [0,1,1]])

[1 4 6]


In [36]:
print(a>5)

[[False False]
 [False False]
 [False  True]]


In [37]:
print(a[a>5])

[6]


In [38]:
a=np.array([0,1,2,3,4,5])
print([a[:3]])

[array([0, 1, 2])]


In [39]:
print(a[2:4])

[2 3]


In [41]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
a[:2,1:3]

array([[2, 3],
       [6, 7]])

In [44]:
sub_array = a[:2,1:3]
print("sub array index [0.0] value change:", sub_array[0,0])
sub_array[0,0] =50
print("sub array index [0,0] value change:", sub_array[0,0])
print("original array index [0,1] value after change:", a[0,1])

sub array index [0.0] value change: 2
sub array index [0,0] value change: 50
original array index [0,1] value after change: 50


In [ ]:
wines = np.genfromtxt("datasets/winequalit-red.csv")